### ISSUE TITLE
A couple issues related to the beta (you just published)

### ISSUE THREAD

**Issue by phaistonian** [thejameskyle/babel-setup-react-transform#1]
(Sorry for posting them here). 

1. When programmatically unmounting a React component errors are thrown. 
2. A full reload is triggered, even though the component properly updates. 

Will send more info info needed. 

Thanks for your efforts.

**Comment by thejameskyle** [comment]
Assuming these are issues with react-transform-hmr?

**Comment by phaistonian** [comment]
Yes.

**Comment by thejameskyle** [comment]
I'm not sure, `react-transform-hmr` hasn't changed at all as the plugin still generates compatible output. Although the IDs it generates are slightly different (but that shouldn't matter).

Can you create a repo that reproduces it?

**Comment by phaistonian** [comment]
I would love to, but this project is a rathed huge one to share or give access to (too many private dependencies anyway). 

I could, if you want, give you anything from screencasts, logs to remote access to my system to check it out.

**Comment by thejameskyle** [comment]
I just mean a simple reproduction case that I can open up and test. I definitely don't want a giant repo with tons and tons of extra code.

For example, I create repos for bugs in Babel all the time: https://github.com/search?q=user%3Athejameskyle+__babel-bug

**Comment by phaistonian** [comment]
Hey James.

I will try and setup one sometime during the day.

Meanwhile, I found out that react-transform-hmr somehow doesn't play well with components extended from other components (Yes, I know it's not a good practice to do so).

The main issue now is get this (attached) all the time.
![image](https://cloud.githubusercontent.com/assets/796530/11681477/dedb4f5e-9e67-11e5-9ef9-074db9c6eead.png)

It probably has something to do with webpack middleware, but I will investigate further.

Again, thank you.
